In [1]:
import logging
import time

import numpy as np
import matplotlib.pyplot as plt

import tensorflow_datasets as tfds
import tensorflow as tf

import tensorflow_text 

In [2]:
text = "Je veux prendre une voiture à l'aéroport"

In [3]:
input_text = tf.constant([text])

In [4]:
reloaded = tf.saved_model.load('attention_translator')

In [5]:
reloaded(input_text).numpy()

array([b'i want to take a car at the airport . [END]'], dtype=object)

In [6]:
reloaded.beam_translate(input_text)

(<tf.Tensor: shape=(1, 3), dtype=string, numpy=
 array([[b'i want to take a car at the airport . [END]',
         b'i want to take a car to the airport . [END]',
         b'i want to have a car at the airport . [END]']], dtype=object)>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ -6.991229, -25.026339, -36.32093 ]], dtype=float32)>)

In [7]:
reloaded = tf.saved_model.load("fra-translator")

In [8]:
reloaded(text)

<tf.Tensor: shape=(), dtype=string, numpy=b'i want to get a car at the airport .'>